apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-usermanagement-pvc
  namespace: usermanagement
  labels:
    type: local
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi