version: '3'
services:
  checkout-db:
    image: postgres
    container_name: checkout-db
    environment:
      POSTGRES_USER: checkout
      POSTGRES_PASSWORD: password
      POSTGRES_DB: checkout
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U checkout"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - usermanagement-db:/var/lib/postgresql/data
    restart: always
    networks:
      - checkoutnet
    
  checkout-app:
    image: checkout-backend:latest
    container_name: checkout-app
    restart: always
    depends_on:
      checkout-db:
        condition: service_healthy
    environment:
      API_URL: "0.0.0.0"
      API_PORT: "8084"
      TRAVEL_API_URL: "http://localhost:8086/api/v1/"
      JWT_SECRET: "your-jwt-secret"
      KAFKA_URL: "kafka:9092"
      TOPIC: "checkout"
      DATABASE_URL: "postgres://checkout:password@checkout-db:5432/checkout"
    ports:
      - "8084:8084"
    networks: 
      - docker_kafka
      - checkoutnet

volumes:
  usermanagement-db:

networks:
  docker_kafka:
    external: true
  checkoutnet: