apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-web-config
data:
  API_URL: "http://mini.local/checkout/api/v1/"
  MONITORING_URL: "http://mini.local/monitor/"
  USERMANAGEMENT_URL: "http://mini.local/users/"
  HOTELMANAGEMENT_URL: "http://mini.local/travma/"
