apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkout-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter_once off;
      sub_filter_types *;
      sub_filter 'href="/' 'href="/cart/';
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /cart(/|$)(.*)
        backend:
          service:
            name: checkout-web-service
            port:
              number: 8083
