apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-nginx-config

data:
  nginx.conf: |
    events {}
    http {
      client_max_body_size 100M;
      include   /etc/nginx/mime.types;

      server {
          listen 8083;

          location / {
              # root /app/dist/;
              root /usr/share/nginx/html;
              index index.html index.htm;
              try_files $uri $uri/ index.html;
          }

          location /cart {
              # root /app/dist/;
              root /usr/share/nginx/html;
              index index.html index.htm;
              try_files $uri $uri/ index.html;
          }

          location /api/ {
              resolver    127.0.0.1   valid=30s;   
                       rewrite ^\/api\/(.*) /$1 break;

              add_header 'Access-Control-Allow-Origin' '*';
              set         $dummy  http://cart-app:8084;
              proxy_pass  $dummy;
          }

      }
    }
