apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-db
spec:
  selector:
    matchLabels:
      app: monitor-pg
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monitor-pg
        tier: backend
    spec:
      containers:
        - image: postgres:16.1-alpine3.19
          name: monitor-pg
          envFrom:
            - configMapRef:
                name: monitor-db-config
            - secretRef:
                name: monitor-db-secret
          ports:
            - containerPort: 5432
              name: monitor-pg
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: monitor-db-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100Mi"      
      volumes:
        - name: monitor-db-storage
          persistentVolumeClaim:
            claimName: db-monitor-pvc