apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-app-config
data:
  API_URL: "0.0.0.0:8088"
  PRODUCTION: "false"
  DEBUG: "true"

  # BROKERS should be just one value
  BROKERS: "kafka-service:9092"

  # DB
  DB_HOST: "monitor-db-service"
  DB_USER: monitoring
  DB_PORT: "5432"
  SSL_TLS: "disable"
  TIMEZONE: "Europe/Berlin"
  DB_NAME: monitoring
  DB_PASSWORD: password