apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermngt-web
  labels:
    app: usermngt-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermngt-web
      tier: frontend
  template:
    metadata:
      labels:
        app: usermngt-web
        tier: frontend
    spec:
      containers:
        - name: usermngt-web
          image: dak4408/travma-usermanagement-frontend:latest
          envFrom:
            - configMapRef: 
                name: usermngt-web-config
          ports:
            - name: usermngt-web
              containerPort: 8081
          imagePullPolicy: Always
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100Mi"
