apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usermngt-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: usermngt-web-service
            port:
              number: 8081