apiVersion: v1
kind: ConfigMap
metadata:
  name: usermngt-app-config
data:
  DOMAIN: "http://mini.local/"
  API_URL: "0.0.0.0:8086"
  PRODUCTION: "false"
  DEBUG: "true"

  # BROKERS should be just one value
  BROKERS: "kafka-service:9092"
  TOPIC: "usermanagement"

  # DB
  DB_HOST: "usermngt-db-service"
  DB_USER: "usermngt"
  DB_NAME: "usermngt"
  DB_PORT: "5432"
  SSL_TLS: "disable"
  TIMEZONE: "Europe/Berlin"
