apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: travelmngt-web-ingress
spec:
    ingressClassName: nginx
    rules:
      - host: mini.local
        http:
          paths:
            - backend:
                service:
                  name: demo
                  port:
                    number: 8085
              path: /travma #prefix has to be processed by pod
              pathType: Prefix