version: '3'
services:
  travelmngt-db:
    image: postgres
    container_name: travelmngt-db
    environment:
      POSTGRES_USER: travelmanagement
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travelmanagement
      PGDATA: /data/travelmanagement
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U travelmanagement" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - travelmngt-db:/data/postgres
    restart: always
    networks:
      - travelmngtnet

  travelmngt-app:
    image: mig3177/travelmanagement
    container_name: travelmngt-app
    restart: always
    ports:
      - "8093:8093"
    depends_on:
      travelmngt-db:
        condition: service_healthy
    environment:
      DOMAIN: :8093
      API_URL: :8093
      JWT_SECRET: your-jwt-secret

      # Change to true when using tls
      PRODUCTION: false

      # Gives additional information of the webserver
      DEBUG: true

      # BROKER Settings
      BROKERS: localhost:9092
      TOPIC: travelmanagement

      # DB Settings
      DB_HOST: travelmngt-db
      DB_USER: travelmanagement
      DB_PASSWORD: password
      DB_NAME: travelmanagement
      DB_PORT: 5432
      SSL_TLS: disable
      TIMEZONE: Europe/Berlin
    networks:
      - publicnet
      - travelmngtnet

  proxy:
    image: nginx:stable-alpine3.17
    ports:
      - "12345:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - travelmngt-app
    networks:
      - travelmngtnet

volumes:
  travelmngt-db:


networks:
  travelmngtnet:
  publicnet:
