version: '3'
services:
  travelmngt-db:
    image: postgres
    container_name: travelmngt-db
    environment:
      POSTGRES_USER: travelmanagement
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travelmanagement
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U travelmanagement" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - travelmngt-db:/var/lib/postgresql/data
    restart: always
    ports:
      - "8096:8096"
    networks:
      - travelmngtnet

  travelmngt-app:
    image: mig3177/travma-travelmanagement-backend:latest
    container_name: travelmngt-app
    restart: always
    depends_on:
      travelmngt-db:
        condition: service_healthy
    environment:
      DOMAIN: :8086
      API_URL: :8086
      JWT_SECRET: your-jwt-secret

      # Change to true when using tls
      PRODUCTION: false

      # Gives additional information of the webserver
      DEBUG: true

      # BROKER Settings
      BROKERS: localhost:9092
      TOPIC: travelmanagement

      # DB Settings
      DB_HOST: travelmngt-db
      DB_USER: travelmanagement
      DB_PASSWORD: password
      DB_NAME: travelmanagement
      DB_PORT: 5432
      SSL_TLS: disable
      TIMEZONE: Europe/Berlin
    ports:
      - "8086:8086"

    networks:
      - publicnet
      - travelmngtnet

  travelmngt-web:
    image: mig3177/travma-travelmanagement-frontend:latest
    container_name: travelmngt-web
    ports:
      - "8085:8085"
    depends_on: 
      - travelmngt-app
    environment:
      API_URL_FR: "http://localhost:8085/api/v1/"
      CHECKOUT_URL: ""
      LOGIN_URL: ""
      MONITOR_URL: ""
    restart: always
    networks:
      - publicnet
    volumes:
      - "./frontend/nginx.conf:/etc/nginx/nginx.conf"

volumes:
  travelmngt-db:

networks:
  travelmngtnet:
  publicnet:
