version: '3'
services:
  usermanagement-db:
    image: postgres
    container_name: usermanagement-db
    environment:
      POSTGRES_USER: usermanagement
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usermanagement
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U usermanagement" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - usermanagement-db:/var/lib/postgresql/data
    restart: always
    networks:
      - dbnetusermanagement

  usermanagement-app:
    image: dak4408/travma-usermanagement-backend:latest
    container_name: usermanagement-backend
    restart: always
    depends_on:
      usermanagement-db:
        condition: service_healthy
    environment:
      DOMAIN: http://usermanagement-frontend:8081
      API_URL: :8082
      
      SALT: your-secret-salt
      JWT_SECRET: your-jwt-secret
      # Change to true when using tls
      PRODUCTION: false
      
      # Gives additional information of the webserver
      DEBUG: true
      # BROKERS should be just one value
      BROKERS: kafka:9092
      TOPIC: usermanagement
      # DB
      DB_HOST: usermanagement-db
      DB_USER: usermanagement
      DB_PASSWORD: password
      DB_NAME: usermanagement
      DB_PORT: 5432
      SSL_TLS: disable
      TIMEZONE: Europe/Berlin

    networks:
      - privatenet
      - dbnetusermanagement

    ports:
      - "8082:8082"

  usermanagement-web:
    image: dak4408/travma-usermanagement-frontend:latest
    container_name: usermanagement-web
    restart: always
    depends_on:
      - usermanagement-app
    environment:
      API_URL: http://localhost:12345/api/v1
      CHECKOUT_URL: http://localhost:12345/cart
      TRAVELMANAGEMENT_URL: http://localhost:12345/travma
      MONITORING_URL: http://localhost:12345/*
    ports:
      - "8081:8081"
    networks:
      - privatenet
      - publicnet
    volumes:
      - "./config/nginx.usermanagement.conf:/etc/nginx/nignx.conf"

volumes:
  usermanagement-db:

networks:
  privatenet:
    external: true

  publicnet:
    external: true

  dbnetusermanagement:
    external: true