version: '3'
services:
  users-db:
    image: postgres
    container_name: users-db
    environment:
      POSTGRES_USER: travelmanagement
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travelmanagement
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U travelmanagement" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - users-db:/var/lib/postgresql/data
    restart: always
    networks:
      - dbnetusers

  usermanagement-app:
    image: dak4408/travma-usermanagement-backend:latest
    container_name: usermanagement-app
    restart: always
    depends_on:
      users-db:
        condition: service_healthy
    environment:
      DOMAIN: http://localhost:12345
      API_URL: :8082
      
      SALT: your-secret-salt
      JWT_SECRET: your-jwt-secret
      # Change to true when using tls
      PRODUCTION: false
      
      # Gives additional information of the webserver
      DEBUG: true
      # BROKERS should be just one value
      BROKERS: kafka:9092
      TOPIC: usermanagement
      # DB
      DB_HOST: users-db
      DB_USER: travelmanagement
      DB_PASSWORD: password
      DB_NAME: travelmanagement
      DB_PORT: 5432
      SSL_TLS: disable
      TIMEZONE: Europe/Berlin

    networks:
      - privatenet
      - dbnetusers

    ports:
      - "8082:8082"

  usermanagement-web:
    image: dak4408/travma-usermanagement-frontend:latest
    container_name: usermanagement-web
    restart: always
    depends_on:
      - usermanagement-app
    environment:
      CHECKOUT_URL: http://localhost:12345/cart
      TRAVELMANAGEMENT_URL: http://localhost:12345/travma
      MONITORING_URL: http://localhost:12345/*
    ports:
      - "8081:8081"
    networks:
      - privatenet
      - publicnet
    volumes:
      - "./config/nginx.usermanagement.conf:/etc/nginx/nginx.conf"

volumes:
  users-db:

networks:
  privatenet:
    external: true

  publicnet:
    external: true

  dbnetusers:
    external: true