version: '3'
services:
  proxy:
    image: nginx:stable-alpine3.17
    container_name: nginx-proxy
    ports:
      - "12345:80"
    volumes:
      - "./config/nginx.proxy.conf:/etc/nginx/nginx.conf"
    networks:
      - publicnet

networks:
  publicnet:
    external: true