# All-in-One solution (still starts different containers) 
# for the checkout microservices 
version: '3'
services:
  postgres:
    image: postgres
    container_name: checkout-db
    restart: always
    environment:
      POSTGRES_USER: checkout
      POSTGRES_PASSWORD: password
      POSTGRES_DB: checkout
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "checkout"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports: 
    - "8094:5432"
    networks:
      - checkoutnet
    volumes:
      # - checkout-db:/var/lib/postgresql/data
      - checkout-db:/data/postgres
    
  backend:
    image: dak4408/travma-checkout-backend:latest
    container_name: checkout-backend
    restart: always
    environment:
      JWT_SECRET: "your-fav-secret"
      KAFKA_URL: "localhost:9092"      
      TOPIC: checkout
      DATABASE_URL: "postgres://checkout:password@localhost:8094/checkout"
    depends_on:
      postgres:
        condition: service_healthy
    # note that this is an security issue
    # network_mode: host
    ports:
      - "8084:8082"
    networks:
      - checkoutnet
      - publicnet    
  
  frontend:
    image: dak4408/travma-usermanagement-frontend:latest
    container_name: usermanagement-frontend
    restart: always
    environment:
      API_URL: "http://localhost:8084"
      USERMANAGEMENT_URL: "http://localhost:8081"
      HOTELMANAGEMENT_URL: "http://localhost:8085"
      MONITORING_URL: "http://localhost:8087"    
    depends_on:
      - backend
    ports:
      - "8083:80"
    networks:
      - publicnet
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf


volumes:
  checkout-db:

networks:
  checkoutnet:
  publicnet: