kind: Service
apiVersion: v1
metadata:
  name: checkout-db-service
spec:
  type: NodePort
  selector:
    app: checkout-pg
    tier: backend
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432