version: '3'
services:
  usermanagement-web:
    image: usermanagement-frontend:latest
    container_name: usermanagement-web
    restart: always
    environment:
      API_URL: http://usermanagement-app:8082/api/v1
      CHECKOUT_URL: http://checkout-frontend:8083/#/cart
      TRAVELMANAGEMENT_URL: http://travelmngt-frontend:8085/#/travma
      MONITORING_URL: http://localhost:8087/*
    ports:
      - "8081:8081"
    volumes:
      - "../nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - docker_usermanagementnet

networks:
  docker_usermanagementnet:
    external: true