apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-travelmngt-pvc
  labels:
    type: local
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi