# 1. Postgres
# 2. Usermanagement Backend
# 3. Usermanagement Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-postgres
  labels:
    app: usermanagement-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: usermanagement-postgres
    template:
      metadata:
        labels:
          app: usermanagement-postgres
      spec:
        containers:
          - name: postgres
            image: postgres:latest
            env:
              - name: POSTGRES_USER
                value: usermanagement
              - name: POSTGRES_PASSWORD
                value: password
              - name: POSTGRES_DB
                value: usermanagement
            ports:
              - containerPort: 8094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-backend
  labels:
    app: usermanagement-backend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: usermanagement-backend
    template:
      metadata:
        labels:
          app: usermanagement-backend
      spec:
        containers:
          - name: usermanagement-backend
            image: dak4408/usermanagement-backend:latest
            env:
              - name: DOMAIN
                value: http://localhost:8081
              - name: API_URL
                value: http://localhost:8082
              - name: SALT
                value: your-secret-salt
              - name: JWT_SECRET
                value: your-jwt-secret
              - name: DEBUG 
                value: "true"
              - name: BROKERS
                value: localhost:9092
              - name: TOPIC
                value: usermanagement
              - name: DB_HOST
                value: localhost
              - name: DB_PORT
                value: "8092"
              - name: DB_USER
                value: usermanagement
              - name: DB_PASSWORD
                value: password
              - name: DB_NAME
                value: usermanagement
              - name: SSL_TLS
                value: "disable"
              - name: TIMEZONE
                value: "Europe/Berlin"
              # only when using with tls 
              - name: PRODUCTION
                value: "false"
            ports:
              - containerPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-frontend
  labels:
    app: usermanagement-frontend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: usermanagement-frontend
    template:
      metadata:
        labels:
          app: usermanagement-frontend
      spec:
        containers:
          - name: usermanagement-frontend
            image: dak4408/usermanagement-frontend:latest
            env:
              - name: VITE_API_URL
                value: http://localhost:8082/api/v1/
              - name: VITE_CHECKOUT_URL
                value: http://localhost:8083/cart
              - name: VITE_TRAVELMANAGEMENT_URL
                value: http://localhost:8085/travma
              -name: VITE_MONITORING_URL
                value: http://localhost:8087/*
            ports:
              - containerPort: 80