# All-in-One solution (still starts different containers) 
# for the usermanagement microservices 
version: '3'
services:
  usermanagement-db:
    image: postgres
    container_name: usermanagement-db
    restart: always

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: usermanagement
      POSTGRES_DB: usermanagement

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U travelmanagement" ]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - usermanagement-db:/var/lib/postgresql/data

    networks:
      - usermanagementnet
      - dbnet

  usermanagement-backend:
    image: dak4408/travma-usermanagement-backend:latest
    container_name: usermanagement-backend
    restart: always
    depends_on:
      usermanagement-db:
        condition: service_healthy
    environment:
      DOMAIN: http://localhost:8081
      API_URL: :8082
      
      SALT: your-secret-salt
      JWT_SECRET: your-jwt-secret

      # Change to true when using tls
      PRODUCTION: false
      
      # Gives additional information of the webserver
      DEBUG: true

      # BROKERS should be just one value
      BROKERS: localhost:9092
      TOPIC: usermanagement

      # DB
      DB_HOST: usermanagement-db
      DB_USER: usermanagement
      DB_PASSWORD: password
      DB_NAME: usermanagement
      DB_PORT: 5432
      SSL_TLS: disable
      TIMEZONE: Europe/Berlin

    ports:
      - "8082:8082"
    networks:
      - usermanagementnet
      - dbnet
  
  frontend:
    image: dak4408/travma-usermanagement-frontend:latest
    container_name: usermanagement-frontend
    restart: always
    environment:
      API_URL: http://usermanagement-backend/api/v1
      CHECKOUT_URL: http://checkout-frontend:8083/#/cart
      TRAVELMANAGEMENT_URL: http://travelmngt-frontend:8085/#/travma
      MONITORING_URL: http://localhost:8087/*
    
    networks: 
      - usermanagementnet
    ports:
      - "8081:80"
    volumes:
      - "./frontend/nginx.conf:/etc/nginx/nignx.conf"

volumes:
  usermanagement-db:

networks:
  publicnet:
  usermanagementnet:
  dbnet:
