apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-app-config
data:
  API_URL: "0.0.0.0"
  API_PORT: "8084"
  PRODUCTION: "false"
  DEBUG: "true"

  # BROKERS should be just one value
  KAFKA_URL: kafka-service:9092
  TOPIC: checkout

  TRAVEL_API_URL: "http://travelmngt-app-service:8086/api/v1"
  DATABASE_URL: "postgres://checkout:password@checkout-db-service:5432/checkout"
  # DB
  DB_HOST: "checkout-db-service"
  DB_USER: checkout
  DB_PORT: "5432"
  SSL_TLS: "disable"
  TIMEZONE: "Europe/Berlin"
  DB_NAME: checkout
  DB_PASSWORD: password