# Runs when PR open event emits if the travel-management directory changed 
# Used for development - build and test which are then uploaded as artifacts for analysis
name: Dev - Travelmanagement backend - security and build 
run-name: ${{ github.actor }} started travelmanagement pipeline
on:
  pull_request:
    types: opened
    branches:
      - develop
      - main
    paths:
      - 'travel-management/backend/**'
      - '!travel-management/backend/**.md'
  workflow_call:
  workflow_dispatch:
  
defaults:
  run: 
    shell: bash
    working-directory: "./travel-management/backend"
  
jobs:
  security:
    name: Security 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.21.5']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: | 
          go get .
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Check
        run: govulncheck -json ./... > VulnerabilityResults-${{ matrix.go-version }}.json
     
      - name: Upload Go vulnerability results
        uses: actions/upload-artifact@v3
        with:
          name: Security-results-${{ matrix.go-version }}
          path: VulnerabilityResults-${{ matrix.go-version }}.json
  
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.21.5']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./tests -json > TestResults-${{ matrix.go-version }}.json
      
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linter
        uses: wearerequired/lint-action@v2
        with: 
          auto_fix: true
          gofmt: true
