# Runs on
name: Dev - Usermanagement frontend - security and build 
run-name: ${{ github.actor }} started usermanagement pipeline
on:
  pull_request:
    types: opened
    branches:
      - develop

defaults:
  run: 
    shell: bash
    working-directory: "./usermanagement/frontend"

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      - run: npm ci
      - run: npm audit

  release-build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present